/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NamiRouteImport } from './routes/nami'
import { Route as MoonClientRouteImport } from './routes/moon-client'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsletterConfirmedRouteImport } from './routes/newsletter.confirmed'
import { Route as ApiPublicNewsletterUnsubscribeRouteImport } from './routes/api/public/newsletter/unsubscribe'
import { Route as ApiPublicNewsletterConfirmRouteImport } from './routes/api/public/newsletter/confirm'

const NamiRoute = NamiRouteImport.update({
  id: '/nami',
  path: '/nami',
  getParentRoute: () => rootRouteImport,
} as any)
const MoonClientRoute = MoonClientRouteImport.update({
  id: '/moon-client',
  path: '/moon-client',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterConfirmedRoute = NewsletterConfirmedRouteImport.update({
  id: '/newsletter/confirmed',
  path: '/newsletter/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsletterUnsubscribeRoute =
  ApiPublicNewsletterUnsubscribeRouteImport.update({
    id: '/api/public/newsletter/unsubscribe',
    path: '/api/public/newsletter/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNewsletterConfirmRoute =
  ApiPublicNewsletterConfirmRouteImport.update({
    id: '/api/public/newsletter/confirm',
    path: '/api/public/newsletter/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/moon-client': typeof MoonClientRoute
  '/nami': typeof NamiRoute
  '/newsletter/confirmed': typeof NewsletterConfirmedRoute
  '/api/public/newsletter/confirm': typeof ApiPublicNewsletterConfirmRoute
  '/api/public/newsletter/unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/moon-client': typeof MoonClientRoute
  '/nami': typeof NamiRoute
  '/newsletter/confirmed': typeof NewsletterConfirmedRoute
  '/api/public/newsletter/confirm': typeof ApiPublicNewsletterConfirmRoute
  '/api/public/newsletter/unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/moon-client': typeof MoonClientRoute
  '/nami': typeof NamiRoute
  '/newsletter/confirmed': typeof NewsletterConfirmedRoute
  '/api/public/newsletter/confirm': typeof ApiPublicNewsletterConfirmRoute
  '/api/public/newsletter/unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/docs'
    | '/moon-client'
    | '/nami'
    | '/newsletter/confirmed'
    | '/api/public/newsletter/confirm'
    | '/api/public/newsletter/unsubscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/docs'
    | '/moon-client'
    | '/nami'
    | '/newsletter/confirmed'
    | '/api/public/newsletter/confirm'
    | '/api/public/newsletter/unsubscribe'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/docs'
    | '/moon-client'
    | '/nami'
    | '/newsletter/confirmed'
    | '/api/public/newsletter/confirm'
    | '/api/public/newsletter/unsubscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  MoonClientRoute: typeof MoonClientRoute
  NamiRoute: typeof NamiRoute
  NewsletterConfirmedRoute: typeof NewsletterConfirmedRoute
  ApiPublicNewsletterConfirmRoute: typeof ApiPublicNewsletterConfirmRoute
  ApiPublicNewsletterUnsubscribeRoute: typeof ApiPublicNewsletterUnsubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nami': {
      id: '/nami'
      path: '/nami'
      fullPath: '/nami'
      preLoaderRoute: typeof NamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moon-client': {
      id: '/moon-client'
      path: '/moon-client'
      fullPath: '/moon-client'
      preLoaderRoute: typeof MoonClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/confirmed': {
      id: '/newsletter/confirmed'
      path: '/newsletter/confirmed'
      fullPath: '/newsletter/confirmed'
      preLoaderRoute: typeof NewsletterConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter/unsubscribe': {
      id: '/api/public/newsletter/unsubscribe'
      path: '/api/public/newsletter/unsubscribe'
      fullPath: '/api/public/newsletter/unsubscribe'
      preLoaderRoute: typeof ApiPublicNewsletterUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter/confirm': {
      id: '/api/public/newsletter/confirm'
      path: '/api/public/newsletter/confirm'
      fullPath: '/api/public/newsletter/confirm'
      preLoaderRoute: typeof ApiPublicNewsletterConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  MoonClientRoute: MoonClientRoute,
  NamiRoute: NamiRoute,
  NewsletterConfirmedRoute: NewsletterConfirmedRoute,
  ApiPublicNewsletterConfirmRoute: ApiPublicNewsletterConfirmRoute,
  ApiPublicNewsletterUnsubscribeRoute: ApiPublicNewsletterUnsubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
